stages:
  - Syntax Check

variables:
  GIT_DEPTH: 1 # No need to bring the whole history
  COLUMNS: 150

  GL_PIPELINE_NAME: 'Dry run test on $CI_COMMIT_BRANCH'
  PCVS_CMD: pcvs run --profile-path ${CI_PROJECT_DIR}/.gitlab/ci/testing_profile.yml --dry-run -S

workflow:
  name: '$GL_PIPELINE_NAME'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        GL_PIPELINE_NAME: '$CI_MERGE_REQUEST_TITLE'

default:
  interruptible: true

before_script:
  - source "$(ccc_home -u mpc)/gitlab-runner/spack_organizer_inti/setup.sh"
  - spack env activate mpc-runner-deps
  - module load mpi
  - export PATH=$PATH:${CI_BUILDS_DIR}/bin

Create HIP Mock:
  stage: '.pre'
  needs: []
  script:
    - mkdir -p ${CI_BUILDS_DIR}/bin 
    - echo "#!/bin/sh" > ${CI_BUILDS_DIR}/bin/hipcc 
    - chmod +x ${CI_BUILDS_DIR}/bin/hipcc

Dry Run Hybrid:
  stage: 'Syntax Check'
  needs: ['Create HIP Mock']
  script:
    - ${PCVS_CMD} Hybrid

Dry Run MPI:
  stage: 'Syntax Check'
  needs: ['Create HIP Mock']
  script:
    - ${PCVS_CMD} MPI

Dry Run OpenMP:
  stage: 'Syntax Check'
  needs: ['Create HIP Mock']
  script:
    - ${PCVS_CMD} OpenMP

# FIXME: Threads/tbb is broken, see #2
Dry Run Threads:
  stage: 'Syntax Check'
  needs: ['Create HIP Mock']
  script:
    - ${PCVS_CMD} Threads/cpp Threads/futex Threads/interfaces

Dry Run accelerators:
  stage: 'Syntax Check'
  needs: ['Create HIP Mock']
  script:
    - ${PCVS_CMD} accelerators

# NOTE: Impossible to fetch Quicksilver submodule
Dry Run applications:
  stage: 'Syntax Check'
  needs: ['Create HIP Mock']
  script:
    - ${PCVS_CMD} applications/Corals applications/Mantevo

Dry Run performance:
  stage: 'Syntax Check'
  needs: ['Create HIP Mock']
  script:
    - ${PCVS_CMD} performance

Dry Run reproducers:
  stage: 'Syntax Check'
  needs: ['Create HIP Mock']
  script:
    - ${PCVS_CMD} reproducers

Dry Run serial:
  stage: 'Syntax Check'
  needs: ['Create HIP Mock']
  script:
    - ${PCVS_CMD} serial
