#Available stages to run in 'automatic' processing:
# For convenience, implicit stages have been made explicit here...
stages:
  - Initialization
  - Basic Testing
  - Regular Testing
  - Applications
  - Finalization

.only_rules: &only_rules
  only:
    - master
    - merge_requests
    - web

############################
##### EXTRA ACTIONS ########
############################
# post-actions to cleanup the machine after the run
# The last line may not be necessary as a pipeline start run something like a "git clean" before running
# This implies a probable issue when multiple piplines are run concurrently on the same project :(
# Please read the CAUTION above !
Artifact Deletion:
  <<: *only_rules
  stage: Finalization
  allow_failure: true
  when: on_success
  script:
    - $HOME/clean_old_pipelines.sh

Resource Relinquishing:
  <<: *only_rules
  stage: Finalization
  allow_failure: true
  when: always
  script:
  - scancel --name GL-build_$CI_PIPELINE_ID

Options:
  <<: *only_rules
  stage: Basic Testing
  script:
  - ./run_validation --help
  - ./run_validation --Version

Listings:
  <<: *only_rules
  stage: Basic Testing
  script:
  - ./run_validation --list-compilers --list-runtimes
  - ./run_validation --list-directories
  - ./run_validation --list-environments
  - ./run_validation --list-variables
  - ./run_validation --list-groups
  - ./run_validation --list-all

Subset run:
  <<: *only_rules
  stage: Regular Testing
  script:
  - ./run_validation --select=applications --compiler=ompi --runtime=ompi --environment=default --expect-success --engine-sim --output=GL_${CI_PIPELINE_ID}/apps

Full Generation:
  <<: *only_rules
  stage: Regular Testing
  script:
  - ./run_validation --engine-sim --output=$HOME/GL_$CI_PIPELINE_ID/full --noexec --expect-success
  cache:
    paths:
      - GL_$CI_PIPELINE_ID/full

# this job should be run after another that created *.xml files (not the case with --noexec option)
Webview:
  <<: *only_rules
  stage: Applications
  script:
  - rm -rf $HOME/GL_$CI_PIPELINE_ID/full/webview/generated/*
  - $HOME/GL_$CI_PIPELINE_ID/full/webview_gen_all.sh --new=GL_$CI_PIPELINE_ID/full/test_suite
  - test -f $HOME/GL_$CI_PIPELINE_ID/full/webview/generated/errors.html || exit 42

