##################################################
# GLOBAL GROUPS, WHICH CAN BE USED DIRECTLY
# IN THE VALIDATION BY REFERENCING THE OBJECT
# WITH ONE OF THE FOLLOWING LABEL:
# ################################################

pcvst_grp_mpi:     &GRPMPI
        n_omp: ~

pcvst_grp_omp:     &GRPOMP
        n_node: ~
        n_proc: ~
        n_mpi: ~
        net: ~

pcvst_grp_hybrid:  &GRPHYB

pcvst_grp_app:     &GRPAPP

pcvst_grp_accl:    &GRPACCL

pcvst_grp_serial:  &GRPSERIAL
        n_node: ~
        n_proc: ~
        n_mpi: ~
        n_omp: ~
        net: ~
        sched: ~
        n_core: [1]

##################################################
# END OF GROUP DEFINITION
##################################################

